// <auto-generated />
using System;
using BrickMoney.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BrickMoney.Migrations
{
    [DbContext(typeof(BrickMoneyDB))]
    [Migration("20210224165950_Init_One")]
    partial class Init_One
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12");

            modelBuilder.Entity("BrickMoney.DB.Models.LegoSetUserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Buyer")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LegoSetId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("PurchasingPrice")
                        .HasColumnType("REAL");

                    b.Property<double>("RetailPrice")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Seller")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoldOver")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LegoSetId");

                    b.ToTable("LegoSetUserInfo");
                });

            modelBuilder.Entity("BrickMoney.LegoSetBasicInfo", b =>
                {
                    b.Property<int>("LegoSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NameDE")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameEN")
                        .HasColumnType("TEXT");

                    b.Property<double>("RrPrice")
                        .HasColumnType("REAL");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("LegoSetId");

                    b.ToTable("BasicInfo");
                });

            modelBuilder.Entity("BrickMoney.DB.Models.LegoSetUserInfo", b =>
                {
                    b.HasOne("BrickMoney.LegoSetBasicInfo", "LegoSetBasic")
                        .WithMany()
                        .HasForeignKey("LegoSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
